Repository Luna-Grace/Marketing-Account-Masking, pull requests merged in 2024-08, with the labels that each got.

#1 初始修改
  .github/workflows/data-format-convert.yml
  .gitignore
  README.md
  bilibili-normal.json
  bilibili_check_uid.py
  bilibili_convert_json.py
Labels: 文档, 存疑, 新功能, 新账号

#2 [自动流🤖]【哔哩哔哩】添加转换后的数据
  bilibili-normal-uids.txt
  bilibili-normal-usernames.txt
  bilibili-normal.md
  bilibili-normal.yaml
Labels: 检查：通过, 新账号

#3 [自动流🤖]【哔哩哔哩】自动添加数据
  bilibili-normal-uids.txt
  bilibili-normal-usernames.txt
  bilibili-normal.json
  bilibili-normal.md
  bilibili-normal.yaml
Labels: 检查：异常, 存疑, 新账号
